### ISSUE TITLE
TIL from Front End TLDR

### ISSUE THREAD

**Issue by caalberts** [ga-students/wdi-sg-discussions#11]
Hi @cbas, if schedule permits this week, could we do a TIL on what we learnt at Front End TLDR?

@tongrhj - elm
@yongjun21 @RoyKoh @zellwk - 3js
@weejh @shawnlimws @caalberts - vue.js

**Comment by cbas** [comment]
Thanks for the reminder @caalberts  -- and everyone for participating! :+1:
