### ISSUE TITLE
Revision Topics

### ISSUE THREAD

**Issue by ongmin** [ga-students/wdi-sg-discussions#18]
Hi guys, as mentioned in class, with just 7 days left to go (3 days already being dedicated to Rails), what are the topics you would like to revise/continue to cover in class? Quick poll to pick the top topics.

Mine (for now):
- continue the CSS breakfasts we've been having (already in the calendar)

**Comment by cbas** [comment]
Thanks for this! See also: https://github.com/ga-students/wdi-sg-organisers/issues?utf8=✓&q=label%3Atopic+
