### ISSUE TITLE
Presentation on using R for data science

### ISSUE THREAD

**Issue by yongjun21** [ga-students/wdi-sg-discussions#3]
Hey guys, l have suggested to Seb since next week we are going to the data science talk by @alyssaq, will be good if we have some basic understanding of the data science tools available. Therefore I will like to do a short presentation on the R programming language. 

I am proposing next Tues morning (15 Dec). Heads up if this sounds good.

**Comment by cbas** [comment]
@yongjun21 :+1: [LGTM](http://www.urbandictionary.com/define.php?term=LGTM&defid=2535452)

**Comment by lisihui** [comment]
@yongjun21 (hey first massage on github!!) sure, presentation on r programming sounds good! it's a closed event for wdi folks, yes, as with the DS talk?

**Comment by ongmin** [comment]
nice! :dancer:

**Comment by cbas** [comment]
@yongjun21 The data science talk (see: #4 ) will take place at 9:00am Tuesday. Do you mind following that up with R lang?

**Comment by cbas** [comment]
@lisihui Congrats on the massage! :speak_no_evil: These two talks (#3 & #4) are part of WDI programme, during regular working hours, and not open to public. The data science talk you are coordinating with @alyssaq would take place on an evening and falls under public GA Classes & Workshops. Apologies for the confusion. :stuck_out_tongue_winking_eye:

**Comment by yongjun21** [comment]
Hi guys, to make the most from my sharing on R tomorrow, it will be good for you to already have R and RStudio installed on your machine. 

1. First install R:
[https://cran.rstudio.com/]https://cran.rstudio.com/

2. Then install RStudio which is the IDE for R:
[https://www.rstudio.com/products/rstudio/download/]https://www.rstudio.com/products/rstudio/download/

3. Open RStudio

4. Goto Tools > Global Options > General. Set up your working directory

5. Goto Tools > Install Packages. Install knitr, ggplot2, wordcloud, zipfR, rpart

**Comment by cbas** [comment]
Thanks for the class! :+1:
