### ISSUE TITLE
Special Session: Data Science

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-discussions#4]
Speaker: @alyssaq
Date: 2015-12-15 (Tuesday)
Time: 09:00 (or slightly earlier)
Duration: 1 hour max

After this session participants will be able to:
- Use online tools for data exploration
- Prepare their Python local environment for data science

**Comment by alyssaq** [comment]
:metal:

**Comment by cbas** [comment]
:heart: Thanks @alyssaq ! Superbly awesome talk.
