### ISSUE TITLE
Special Session: Web Audio

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-discussions#5]
Speaker: @notthetup
Date: 2015-12-18 (Friday)
Time: 12:00 (talk starts after lunch)
Duration: Afternoon

Before the class participants need to:
- Bring earphones/headphones
- Read 
 - Chapter 1 of the [Web Audio API Book](http://chimera.labs.oreilly.com/books/1234000001552/ch01.html#s00_1)
 - [Web Audio API Getting Started](http://creativejs.com/resources/web-audio-api-getting-started/)
- Install [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/)

After this session participants will be able to:
- Make some beats

**Comment by notthetup** [comment]
Before the class participants need to:

- Read 
 - Chapter 1 of the [Web Audio API Book](http://chimera.labs.oreilly.com/books/1234000001552/ch01.html#s00_1)
 - [Web Audio API Getting Started](http://creativejs.com/resources/web-audio-api-getting-started/)

- Install [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/)

**Comment by cbas** [comment]
Thanks for the session!
