### ISSUE TITLE
Special Session: Coding & Electronics

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-discussions#6]
Speaker: @sayanee
Date: 2015-01
Time: 12:00 (talk starts after lunch)
Duration: Afternoon

Before the class participants need to:
- *Read an article...*
- *Install some tool...*

After this session participants will be able to:
- *Build apps with some features...*
- *Explain something...*

**Comment by sayanee** [comment]
:+1:

**Comment by sayanee** [comment]
:+1:

**Comment by sayanee** [comment]
in progress: http://talks.sayan.ee/web-sensors at https://github.com/sayanee/talks/tree/gh-pages/web-sensors

**Comment by sayanee** [comment]
1. [slides](http://talks.sayan.ee/web-sensors)
- [sample code](https://github.com/sayanee/talks/tree/gh-pages/web-sensors/code)
- [electronics list](https://github.com/sayanee/talks/tree/gh-pages/web-sensors#for-everyone) needed from 12Geeks and the students should have them prior to the class

@elfgoh @fazman @cbas feedback welcome :heart_eyes:

**Comment by cbas** [comment]
Based off the FB/email conversations it looks like this has grown into a weekend session. Nice to have it open to broader audience. Also solves the budgeting problem. GA WDI students can use their available GA credits to attend for free.
