### ISSUE TITLE
Special Session: Creative Coding

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-discussions#8]
Speaker: @yinshanyang
Date: 2015-01-25
Time: 14:30–17:00
Duration: Afternoon

See: https://www.futurelearn.com/courses/creative-coding/

Before the class participants need to:
- *Read an article...*
- *Watch a video...*
- *Install some tool...*

After this session participants will be able to:
- Visualise data in interesting & meaningful ways (datavis)
- Create rich and engaging effects or animations (demoscene)

**Comment by cbas** [comment]
Other topics (including RoR) are getting priority as well as emphasis on projects. :disappointed_relieved:

**Comment by cbas** [comment]
Resurrecting this as an afternoon session by @yinshanyang . :sparkles:

**Comment by zz85** [comment]
:+1:
